database:
  path: db/malware_analysis.db

vmray:
  server: VMRAY_HOST
  api_key: YOUR_API_KEY
  sample_types:
    - Unknown
    - Apple Script
    - CFB File
    - Custom
    - Email (EML)
    - Email (MSG)
    - Excel Document
    - HTML Application
    - HTML Application (Shell Link)
    - HTML Document
    - Hanword Document
    - JScript
    - Java Archive
    - Java Class
    - macOS App
    - macOS DMG
    - macOS Executable (Mach-O)
    - macOS PKG
    - Macromedia Flash
    - MHTML Document
    - Microsoft Access Database
    - Microsoft Project Document
    - Microsoft Publisher Document
    - Microsoft Visio Document
    - MSI Setup
    - PDF Document
    - PowerShell Script
    - PowerShell Script (Shell Link)
    - Powerpoint Document
    - Python Script
    - RTF Document
    - Shell Script
    - URL
    - VBScript
    - Windows ActiveX Control (x86-32)
    - Windows ActiveX Control (x86-64)
    - Windows Batch File
    - Windows Batch File (Shell Link)
    - Windows DLL (x86-32)
    - Windows DLL (x86-64)
    - Windows Driver (x86-32)
    - Windows Driver (x86-64)
    - Windows Exe (Shell Link)
    - Windows Exe (x86-32)
    - Windows Exe (x86-64)
    - Windows Help File
    - Windows Script File
    - Word Document

data_dir: data

